import { buildExecuteCommand } from "../package-manager.js";
import {
  addScripts,
  findExistingFile,
  installDevDependencies,
  type SetupContext,
} from "./setup-context.js";

const oxfmtConfigFileName = ".oxfmtrc.json";

// Config formats oxfmt loads (see `oxfmt --help`, --config). `oxfmt --init` exits
// with an error when any of them exists, which would abort the whole run
//
const oxfmtConfigFileNames = [
  ".oxfmtrc.json",
  ".oxfmtrc.jsonc",
  "oxfmt.config.cjs",
  "oxfmt.config.cts",
  "oxfmt.config.js",
  "oxfmt.config.mjs",
  "oxfmt.config.mts",
  "oxfmt.config.ts",
];

// oxfmt with its default (Prettier compatible) style, generated by `oxfmt --init`.
// `fmt` only checks so it can run in CI; `fmt:fix` rewrites files
//
export function setupOxfmt(context: SetupContext): void {
  installDevDependencies(context, ["oxfmt"]);

  const existingConfigFileName = findExistingFile(context, oxfmtConfigFileNames);
  if (existingConfigFileName) {
    context.report.skipped.push(`oxfmt config (${existingConfigFileName} already exists)`);
  } else {
    context.runCommand(
      buildExecuteCommand(context.packageManager, "oxfmt", ["--init"]),
      context.projectDirectory,
    );
    context.report.created.push(oxfmtConfigFileName);
  }

  addScripts(context, { fmt: "oxfmt --check", "fmt:fix": "oxfmt" });
}
