import { buildExecuteCommand } from "../package-manager.js";
import {
  addScripts,
  fileExists,
  installDevDependencies,
  type SetupContext,
} from "./setup-context.js";

const oxfmtConfigFileName = ".oxfmtrc.json";

// oxfmt with its default (Prettier compatible) style, generated by `oxfmt --init`.
// `fmt` only checks so it can run in CI; `fmt:fix` rewrites files
//
export function setupOxfmt(context: SetupContext): void {
  installDevDependencies(context, ["oxfmt"]);

  if (fileExists(context, oxfmtConfigFileName)) {
    context.report.skipped.push(`${oxfmtConfigFileName} (already exists)`);
  } else {
    context.runCommand(
      buildExecuteCommand(context.packageManager, "oxfmt", ["--init"]),
      context.projectDirectory,
    );
    context.report.created.push(oxfmtConfigFileName);
  }

  addScripts(context, { fmt: "oxfmt --check", "fmt:fix": "oxfmt" });
}
