import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { buildExecuteCommand } from "../package-manager.js";
import {
  addScripts,
  fileExists,
  findExistingFile,
  installDevDependencies,
  type SetupContext,
} from "./setup-context.js";

const oxlintConfigFileName = ".oxlintrc.json";

// Config formats oxlint loads (see `oxlint --help`, --config). `oxlint --init`
// ignores the other formats and would create a second, competing .oxlintrc.json
//
const oxlintConfigFileNames = [
  ".oxlintrc.json",
  ".oxlintrc.jsonc",
  "oxlint.config.cjs",
  "oxlint.config.cts",
  "oxlint.config.js",
  "oxlint.config.mjs",
  "oxlint.config.mts",
  "oxlint.config.ts",
];

// oxlint with its default rule set, generated by `oxlint --init` so we follow
// upstream defaults instead of maintaining our own copy.
// TypeScript projects also get type-aware rules (e.g. no-floating-promises) through
// oxlint-tsgolint: https://oxc.rs/docs/guide/usage/linter/type-aware
//
export function setupOxlint(context: SetupContext): void {
  const isTypeScriptProject = fileExists(context, "tsconfig.json");
  installDevDependencies(context, isTypeScriptProject ? ["oxlint", "oxlint-tsgolint"] : ["oxlint"]);

  const existingConfigFileName = findExistingFile(context, oxlintConfigFileNames);
  if (existingConfigFileName) {
    context.report.skipped.push(`oxlint config (${existingConfigFileName} already exists)`);
  } else {
    initializeOxlintConfig(context, isTypeScriptProject);
  }

  addScripts(context, { lint: "oxlint", "lint:fix": "oxlint --fix" });
}

function initializeOxlintConfig(context: SetupContext, isTypeScriptProject: boolean): void {
  context.runCommand(
    buildExecuteCommand(context.packageManager, "oxlint", ["--init"]),
    context.projectDirectory,
  );

  // Guards against a future oxlint release renaming or skipping the generated file
  //
  const configPath = path.join(context.projectDirectory, oxlintConfigFileName);
  if (!existsSync(configPath)) {
    const typeAwareHint = isTypeScriptProject ? " and enable type-aware linting" : "";
    context.report.notices.push(
      `oxlint --init did not create ${oxlintConfigFileName}; create it manually${typeAwareHint}`,
    );
    return;
  }

  context.report.created.push(oxlintConfigFileName);
  if (isTypeScriptProject) {
    enableTypeAwareLinting(configPath);
  }
}

// `typeAware` enables the type-aware rules, `typeCheck` also reports TypeScript
// compiler errors as lint errors
//
export function enableTypeAwareLinting(configPath: string): void {
  const oxlintConfig = JSON.parse(readFileSync(configPath, "utf8")) as Record<string, unknown>;
  const existingOptions =
    typeof oxlintConfig.options === "object" && oxlintConfig.options !== null
      ? oxlintConfig.options
      : {};
  oxlintConfig.options = { ...existingOptions, typeAware: true, typeCheck: true };
  writeFileSync(configPath, `${JSON.stringify(oxlintConfig, null, 2)}\n`);
}
